version: '3.4'
services:
  test-pyaddepar:
     build:
       context: .
       dockerfile: Dockerfile
       target: test
     volumes:
        # change the folder on the left to direct your logs to...
        - ./pyaddepar:/pyaddepar/pyaddepar:ro
        #- ./data:/data
        - ./test:/pyaddepar/test:ro
        - ./source:/source:ro
        - ./build:/build
        - ./html-coverage:/html-coverage
        - ./html-report:/html-report

     working_dir: /pyaddepar
