version: '2'
services:
  pyaddepar:
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
        # change the folder on the left to direct your logs to...
        - ./pyaddepar:/pyaddepar/pyaddepar
        - ./data:/data

     command: /bin/bash

     working_dir: /pyaddepar

     env_file:
      - .env
