version: '2'
services:
  pyaddepar:
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
        # change the folder on the left to direct your logs to...
        - /media/h/thomas/log:/log
     command: /bin/bash
     environment:
        - AFIRM=1
        - AKEY=2
        - ASECRET=3
        - FIGIKEY=4
