version: '3.4'
services:
  addepar:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder

    # point to your notebooks
    #volumes:
    #  - /media/j/notebooks:${WORK}

    # create the .config.ini file with
    #AFIRM=...
    #AKEY=2c...
    #ASECRET=hh...
    #COMPANY=xyz
    env_file:
      - .config


  jupyter:
    build:
      context: .
      dockerfile: binder/Dockerfile
      target: jupyter

    volumes:
      - ./binder/example.ipynb:/home/jovyan/work/example.ipynb

    ports:
      - "4444:8888"

