version: '3.4'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./work:/home/${NB_USER}/work

    env_file:
      - .config
    ports:
      - ${PORT}:8888
