version: '2'
services:
  pyaddepar:
     build:
       context: .
       dockerfile: Dockerfile
     command: /bin/bash
     environment:
        - AFIRM=1
        - AKEY=2
        - ASECRET=3
        - FIGIKEY=4
