version: '3.4'
services:
  test:
     build:
       context: .
       dockerfile: Dockerfile
       target: test
     volumes:
        # change the folder on the left to direct your logs to...
        - ./pyaddepar:/pyaddepar/pyaddepar:ro
        - ./test:/pyaddepar/test:ro
        - ./source:/source:ro
        - ./artifacts:/pyaddepar/artifacts

     working_dir: /pyaddepar

     env_file:
       - test/.env-test
