version: '3.4'
services:
  pyaddepar:
     build:
       context: .
       dockerfile: Dockerfile
       target: test
     volumes:
        # change the folder on the left to direct your logs to...
        - ./pyaddepar:/pyaddepar/pyaddepar
        - ./data:/data

     command: /bin/bash

     working_dir: /pyaddepar

     env_file:
      - .env
     links:
       - test-postgresql
       - test-influxdb

  test-postgresql:
     image: postgres:9.6
     environment:
        POSTGRES_PASSWORD: "test"

  test-influxdb:
     image: influxdb:1.5.4