version: '3.6'
services:
  addepar:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder

    # create the .config.ini file with
    #AFIRM=...
    #AKEY=2c...
    #ASECRET=hh...
    #COMPANY=xyz
    #env_file:
    #  - .config
