version: '3.4'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./work:/home/${NB_USER}/work

    env_file:
      - .config
    ports:
      - ${PORT}:8888

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      # change the folder on the left to direct your logs to...
      - ./pyaddepar:/home/${NB_USER}/work/pyaddepar:ro
      - ./test:/home/${NB_USER}/work/test:ro
      - ./source:/source:ro
      - ./artifacts:/pyaddepar/artifacts

    #working_dir: /pyaddepar

    env_file:
      - test/.env-test
