version: '3.3'
services:
  sut:
    build:
       context: .
       dockerfile: Dockerfile
    volumes:
        # change the folder on the left to direct your logs to...
        - ./test:/pyaddepar/test