version: '2'
services:
  sut:
    build:
       context: .
       dockerfile: Dockerfile-Test
    volumes:
        # change the folder on the left to direct your logs to...
        - ./test:/pyaddepar/test