version: '3.4'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder

    # point to your notebooks
    volumes:
      - /media/j/notebooks:/home/${NB_USER}/work

    # create the .config file with
    #AFIRM=...
    #AKEY=2c...
    #ASECRET=hh...
    #COMPANY=xyz
    env_file:
      - .config

    ports:
      - ${PORT}:8888
