version: '3.4'
services:
  test-pyaddepar:
     build:
       context: .
       dockerfile: Dockerfile
       target: test
     volumes:
        # change the folder on the left to direct your logs to...
        - ./pyaddepar:/pyaddepar/pyaddepar
        - ./data:/data
        - ./test:/pyaddepar/test
        - ./source:/pyaddepar/source:ro
        - ./build:/pyaddepar/build
        - ./html-coverage:/html-coverage
        - ./html-report:/html-report

     working_dir: /pyaddepar
