version: '3.4'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./test:${WORK}/test:ro
      - ./source:/source:ro
      - ./artifacts:${WORK}/artifacts
    env_file:
      - test/.env-test
    user: root
